<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <NeutralLanguage>en</NeutralLanguage>
    <Authors>Inventory Management</Authors>
    <Product>Inventory Management</Product>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

</Project>
