<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>InventoryManagement.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryManagement.Core\InventoryManagement.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="InventoryManagement.Domain.Tests" />
    <InternalsVisibleTo Include="InventoryManagement.Infrastructure" />
    <InternalsVisibleTo Include="InventoryManagement.Infrastructure.Postgres" />
  </ItemGroup>

</Project>
